export type ExerciseCategory =
  | "upper_body"
  | "legs"
  | "abdominal_core"
  | "cardio"
  | "full_body"
  | "mobility_recovery"

export interface ExerciseCatalogItem {
  id: string
  name: string
  category: ExerciseCategory
  primaryMuscleGroup: string
  equipment: string
  isTimed: boolean
  defaultSets: number
  defaultRepsOrDuration: string
  aliases: string[]
  youtubeSearch: string
}

export type ExerciseCategoryMeta = {
  id: ExerciseCategory
  label: string
  shortLabel: string
}

export const EXERCISE_CATEGORY_META: ExerciseCategoryMeta[] = [
  { id: "upper_body", label: "Upper Body", shortLabel: "Upper" },
  { id: "legs", label: "Legs", shortLabel: "Legs" },
  { id: "abdominal_core", label: "Abdominal/Core", shortLabel: "Core" },
  { id: "cardio", label: "Cardio", shortLabel: "Cardio" },
  { id: "full_body", label: "Full Body", shortLabel: "Full" },
  { id: "mobility_recovery", label: "Mobility/Recovery", shortLabel: "Recovery" },
]

export const EXERCISE_CATEGORY_LABELS: Record<ExerciseCategory, string> = Object.fromEntries(
  EXERCISE_CATEGORY_META.map((meta) => [meta.id, meta.label])
) as Record<ExerciseCategory, string>

export const WORKOUT_EXERCISE_CATALOG: ExerciseCatalogItem[] = [
  {
    id: "catalog-upper-bench-press",
    name: "Bench Press",
    category: "upper_body",
    primaryMuscleGroup: "Chest",
    equipment: "Barbell",
    isTimed: false,
    defaultSets: 4,
    defaultRepsOrDuration: "6-10",
    aliases: ["flat bench", "barbell bench"],
    youtubeSearch: "barbell+bench+press+form+tutorial",
  },
  {
    id: "catalog-upper-incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    category: "upper_body",
    primaryMuscleGroup: "Chest",
    equipment: "Dumbbells",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "8-12",
    aliases: ["incline db press", "incline press"],
    youtubeSearch: "incline+dumbbell+press+form",
  },
  {
    id: "catalog-upper-overhead-press",
    name: "Overhead Press",
    category: "upper_body",
    primaryMuscleGroup: "Shoulders",
    equipment: "Barbell or Dumbbells",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "6-10",
    aliases: ["shoulder press", "ohp"],
    youtubeSearch: "overhead+press+form+tutorial",
  },
  {
    id: "catalog-upper-lateral-raise",
    name: "Lateral Raise",
    category: "upper_body",
    primaryMuscleGroup: "Shoulders",
    equipment: "Dumbbells",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "12-15",
    aliases: ["db lateral raise", "side raise"],
    youtubeSearch: "dumbbell+lateral+raise+form",
  },
  {
    id: "catalog-upper-pull-up",
    name: "Pull-up",
    category: "upper_body",
    primaryMuscleGroup: "Back",
    equipment: "Pull-up Bar",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "6-10",
    aliases: ["pull up", "chin-up"],
    youtubeSearch: "pull+up+form+tutorial",
  },
  {
    id: "catalog-upper-lat-pulldown",
    name: "Lat Pulldown",
    category: "upper_body",
    primaryMuscleGroup: "Back",
    equipment: "Cable Machine",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "8-12",
    aliases: ["lat pull", "pulldown"],
    youtubeSearch: "lat+pulldown+form",
  },
  {
    id: "catalog-upper-barbell-row",
    name: "Barbell Row",
    category: "upper_body",
    primaryMuscleGroup: "Back",
    equipment: "Barbell",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "6-10",
    aliases: ["bent-over row", "bb row"],
    youtubeSearch: "barbell+row+form+tutorial",
  },
  {
    id: "catalog-upper-seated-cable-row",
    name: "Seated Cable Row",
    category: "upper_body",
    primaryMuscleGroup: "Back",
    equipment: "Cable Machine",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "8-12",
    aliases: ["cable row", "seated row"],
    youtubeSearch: "seated+cable+row+form",
  },
  {
    id: "catalog-upper-biceps-curl",
    name: "Biceps Curl",
    category: "upper_body",
    primaryMuscleGroup: "Biceps",
    equipment: "Dumbbells or Barbell",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "10-12",
    aliases: ["bicep curl", "curl"],
    youtubeSearch: "biceps+curl+form",
  },
  {
    id: "catalog-upper-triceps-pushdown",
    name: "Triceps Pushdown",
    category: "upper_body",
    primaryMuscleGroup: "Triceps",
    equipment: "Cable Machine",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "10-15",
    aliases: ["tricep pushdown", "rope pushdown"],
    youtubeSearch: "triceps+pushdown+form",
  },
  {
    id: "catalog-legs-back-squat",
    name: "Back Squat",
    category: "legs",
    primaryMuscleGroup: "Quads/Glutes",
    equipment: "Barbell",
    isTimed: false,
    defaultSets: 4,
    defaultRepsOrDuration: "5-8",
    aliases: ["barbell squat"],
    youtubeSearch: "back+squat+form",
  },
  {
    id: "catalog-legs-front-squat",
    name: "Front Squat",
    category: "legs",
    primaryMuscleGroup: "Quads",
    equipment: "Barbell",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "5-8",
    aliases: ["barbell front squat"],
    youtubeSearch: "front+squat+form",
  },
  {
    id: "catalog-legs-leg-press",
    name: "Leg Press",
    category: "legs",
    primaryMuscleGroup: "Quads",
    equipment: "Leg Press Machine",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "10-15",
    aliases: ["machine leg press"],
    youtubeSearch: "leg+press+form",
  },
  {
    id: "catalog-legs-romanian-deadlift",
    name: "Romanian Deadlift",
    category: "legs",
    primaryMuscleGroup: "Hamstrings",
    equipment: "Barbell or Dumbbells",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "6-10",
    aliases: ["rdl"],
    youtubeSearch: "romanian+deadlift+form",
  },
  {
    id: "catalog-legs-walking-lunge",
    name: "Walking Lunge",
    category: "legs",
    primaryMuscleGroup: "Quads/Glutes",
    equipment: "Dumbbells",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "10 each leg",
    aliases: ["lunges", "walking lunges"],
    youtubeSearch: "walking+lunge+form",
  },
  {
    id: "catalog-legs-leg-extension",
    name: "Leg Extension",
    category: "legs",
    primaryMuscleGroup: "Quads",
    equipment: "Leg Extension Machine",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "10-15",
    aliases: ["quad extension"],
    youtubeSearch: "leg+extension+form",
  },
  {
    id: "catalog-legs-leg-curl",
    name: "Leg Curl",
    category: "legs",
    primaryMuscleGroup: "Hamstrings",
    equipment: "Leg Curl Machine",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "10-15",
    aliases: ["hamstring curl"],
    youtubeSearch: "leg+curl+form",
  },
  {
    id: "catalog-legs-hip-thrust",
    name: "Hip Thrust",
    category: "legs",
    primaryMuscleGroup: "Glutes",
    equipment: "Barbell or Machine",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "8-12",
    aliases: ["glute bridge thrust"],
    youtubeSearch: "hip+thrust+form",
  },
  {
    id: "catalog-legs-calf-raise",
    name: "Calf Raise",
    category: "legs",
    primaryMuscleGroup: "Calves",
    equipment: "Machine or Bodyweight",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "12-20",
    aliases: ["standing calf raise"],
    youtubeSearch: "calf+raise+form",
  },
  {
    id: "catalog-legs-goblet-squat",
    name: "Goblet Squat",
    category: "legs",
    primaryMuscleGroup: "Quads/Glutes",
    equipment: "Dumbbell",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "8-12",
    aliases: ["db goblet squat"],
    youtubeSearch: "goblet+squat+form",
  },
  {
    id: "catalog-core-plank",
    name: "Plank",
    category: "abdominal_core",
    primaryMuscleGroup: "Core",
    equipment: "Bodyweight",
    isTimed: true,
    defaultSets: 3,
    defaultRepsOrDuration: "30-60 sec",
    aliases: ["front plank"],
    youtubeSearch: "plank+form",
  },
  {
    id: "catalog-core-side-plank",
    name: "Side Plank",
    category: "abdominal_core",
    primaryMuscleGroup: "Obliques",
    equipment: "Bodyweight",
    isTimed: true,
    defaultSets: 3,
    defaultRepsOrDuration: "20-45 sec",
    aliases: ["side plank hold"],
    youtubeSearch: "side+plank+form",
  },
  {
    id: "catalog-core-dead-bug",
    name: "Dead Bug",
    category: "abdominal_core",
    primaryMuscleGroup: "Core",
    equipment: "Bodyweight",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "8-12 each side",
    aliases: ["deadbug"],
    youtubeSearch: "dead+bug+exercise+form",
  },
  {
    id: "catalog-core-bicycle-crunch",
    name: "Bicycle Crunch",
    category: "abdominal_core",
    primaryMuscleGroup: "Abdominals",
    equipment: "Bodyweight",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "12-20",
    aliases: ["bicycle crunches"],
    youtubeSearch: "bicycle+crunch+form",
  },
  {
    id: "catalog-core-hanging-leg-raise",
    name: "Hanging Leg Raise",
    category: "abdominal_core",
    primaryMuscleGroup: "Abdominals",
    equipment: "Pull-up Bar",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "8-12",
    aliases: ["leg raise hanging"],
    youtubeSearch: "hanging+leg+raise+form",
  },
  {
    id: "catalog-core-cable-crunch",
    name: "Cable Crunch",
    category: "abdominal_core",
    primaryMuscleGroup: "Abdominals",
    equipment: "Cable Machine",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "10-15",
    aliases: ["kneeling cable crunch"],
    youtubeSearch: "cable+crunch+form",
  },
  {
    id: "catalog-core-russian-twist",
    name: "Russian Twist",
    category: "abdominal_core",
    primaryMuscleGroup: "Obliques",
    equipment: "Bodyweight or Plate",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "16-24",
    aliases: ["twists"],
    youtubeSearch: "russian+twist+form",
  },
  {
    id: "catalog-core-ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    category: "abdominal_core",
    primaryMuscleGroup: "Core",
    equipment: "Ab Wheel",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "6-12",
    aliases: ["ab rollout", "wheel rollout"],
    youtubeSearch: "ab+wheel+rollout+form",
  },
  {
    id: "catalog-core-hollow-hold",
    name: "Hollow Hold",
    category: "abdominal_core",
    primaryMuscleGroup: "Core",
    equipment: "Bodyweight",
    isTimed: true,
    defaultSets: 3,
    defaultRepsOrDuration: "20-45 sec",
    aliases: ["hollow body hold"],
    youtubeSearch: "hollow+hold+form",
  },
  {
    id: "catalog-core-bird-dog",
    name: "Bird Dog",
    category: "abdominal_core",
    primaryMuscleGroup: "Core",
    equipment: "Bodyweight",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "8-12 each side",
    aliases: ["bird-dog"],
    youtubeSearch: "bird+dog+exercise+form",
  },
  {
    id: "catalog-cardio-treadmill-run",
    name: "Treadmill Run",
    category: "cardio",
    primaryMuscleGroup: "Cardio",
    equipment: "Treadmill",
    isTimed: true,
    defaultSets: 1,
    defaultRepsOrDuration: "15-30 min",
    aliases: ["run", "jog"],
    youtubeSearch: "treadmill+running+form",
  },
  {
    id: "catalog-cardio-incline-walk",
    name: "Incline Walk",
    category: "cardio",
    primaryMuscleGroup: "Cardio",
    equipment: "Treadmill",
    isTimed: true,
    defaultSets: 1,
    defaultRepsOrDuration: "15-30 min",
    aliases: ["incline treadmill walk"],
    youtubeSearch: "incline+walk+treadmill",
  },
  {
    id: "catalog-cardio-rowing-machine",
    name: "Rowing Machine",
    category: "cardio",
    primaryMuscleGroup: "Cardio",
    equipment: "Rower",
    isTimed: true,
    defaultSets: 1,
    defaultRepsOrDuration: "10-20 min",
    aliases: ["erg", "rower"],
    youtubeSearch: "rowing+machine+technique",
  },
  {
    id: "catalog-cardio-bike-intervals",
    name: "Bike Intervals",
    category: "cardio",
    primaryMuscleGroup: "Cardio",
    equipment: "Stationary Bike",
    isTimed: true,
    defaultSets: 6,
    defaultRepsOrDuration: "30 sec",
    aliases: ["cycling intervals", "spin intervals"],
    youtubeSearch: "stationary+bike+intervals",
  },
  {
    id: "catalog-cardio-stair-climber",
    name: "Stair Climber",
    category: "cardio",
    primaryMuscleGroup: "Cardio",
    equipment: "Stair Climber",
    isTimed: true,
    defaultSets: 1,
    defaultRepsOrDuration: "10-20 min",
    aliases: ["stairs machine"],
    youtubeSearch: "stair+climber+workout",
  },
  {
    id: "catalog-cardio-jump-rope",
    name: "Jump Rope",
    category: "cardio",
    primaryMuscleGroup: "Cardio",
    equipment: "Jump Rope",
    isTimed: true,
    defaultSets: 5,
    defaultRepsOrDuration: "45 sec",
    aliases: ["skipping", "rope jumps"],
    youtubeSearch: "jump+rope+technique",
  },
  {
    id: "catalog-cardio-assault-bike",
    name: "Assault Bike",
    category: "cardio",
    primaryMuscleGroup: "Cardio",
    equipment: "Assault Bike",
    isTimed: true,
    defaultSets: 6,
    defaultRepsOrDuration: "20 sec",
    aliases: ["air bike"],
    youtubeSearch: "assault+bike+intervals",
  },
  {
    id: "catalog-cardio-elliptical-steady-state",
    name: "Elliptical Steady State",
    category: "cardio",
    primaryMuscleGroup: "Cardio",
    equipment: "Elliptical",
    isTimed: true,
    defaultSets: 1,
    defaultRepsOrDuration: "20-30 min",
    aliases: ["elliptical"],
    youtubeSearch: "elliptical+workout",
  },
  {
    id: "catalog-cardio-hiit-sprints",
    name: "HIIT Sprints",
    category: "cardio",
    primaryMuscleGroup: "Cardio",
    equipment: "Track or Treadmill",
    isTimed: true,
    defaultSets: 8,
    defaultRepsOrDuration: "20 sec",
    aliases: ["sprint intervals"],
    youtubeSearch: "hiit+sprint+intervals",
  },
  {
    id: "catalog-cardio-brisk-walk",
    name: "Brisk Walk",
    category: "cardio",
    primaryMuscleGroup: "Cardio",
    equipment: "Bodyweight",
    isTimed: true,
    defaultSets: 1,
    defaultRepsOrDuration: "20-40 min",
    aliases: ["power walk"],
    youtubeSearch: "brisk+walk+benefits",
  },
  {
    id: "catalog-full-deadlift",
    name: "Deadlift",
    category: "full_body",
    primaryMuscleGroup: "Posterior Chain",
    equipment: "Barbell",
    isTimed: false,
    defaultSets: 4,
    defaultRepsOrDuration: "3-6",
    aliases: ["barbell deadlift"],
    youtubeSearch: "deadlift+form+tutorial",
  },
  {
    id: "catalog-full-thruster",
    name: "Thruster",
    category: "full_body",
    primaryMuscleGroup: "Full Body",
    equipment: "Barbell or Dumbbells",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "8-12",
    aliases: ["db thruster"],
    youtubeSearch: "thruster+exercise+form",
  },
  {
    id: "catalog-full-kettlebell-swing",
    name: "Kettlebell Swing",
    category: "full_body",
    primaryMuscleGroup: "Posterior Chain",
    equipment: "Kettlebell",
    isTimed: false,
    defaultSets: 4,
    defaultRepsOrDuration: "12-20",
    aliases: ["kb swing"],
    youtubeSearch: "kettlebell+swing+form",
  },
  {
    id: "catalog-full-burpee",
    name: "Burpee",
    category: "full_body",
    primaryMuscleGroup: "Full Body",
    equipment: "Bodyweight",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "10-15",
    aliases: ["burpees"],
    youtubeSearch: "burpee+form",
  },
  {
    id: "catalog-full-man-maker",
    name: "Man Maker",
    category: "full_body",
    primaryMuscleGroup: "Full Body",
    equipment: "Dumbbells",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "6-10",
    aliases: ["dumbbell man maker"],
    youtubeSearch: "man+maker+exercise+form",
  },
  {
    id: "catalog-full-clean-and-press",
    name: "Clean and Press",
    category: "full_body",
    primaryMuscleGroup: "Full Body",
    equipment: "Barbell or Dumbbells",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "6-10",
    aliases: ["clean press"],
    youtubeSearch: "clean+and+press+form",
  },
  {
    id: "catalog-full-farmer-carry",
    name: "Farmer Carry",
    category: "full_body",
    primaryMuscleGroup: "Grip/Core",
    equipment: "Dumbbells or Kettlebells",
    isTimed: true,
    defaultSets: 4,
    defaultRepsOrDuration: "30 sec",
    aliases: ["farmer walk"],
    youtubeSearch: "farmer+carry+form",
  },
  {
    id: "catalog-full-wall-ball",
    name: "Wall Ball",
    category: "full_body",
    primaryMuscleGroup: "Full Body",
    equipment: "Medicine Ball",
    isTimed: false,
    defaultSets: 4,
    defaultRepsOrDuration: "12-20",
    aliases: ["wall balls"],
    youtubeSearch: "wall+ball+exercise+form",
  },
  {
    id: "catalog-full-sled-push",
    name: "Sled Push",
    category: "full_body",
    primaryMuscleGroup: "Legs/Core",
    equipment: "Sled",
    isTimed: true,
    defaultSets: 5,
    defaultRepsOrDuration: "20 sec",
    aliases: ["prowler push"],
    youtubeSearch: "sled+push+form",
  },
  {
    id: "catalog-full-turkish-get-up",
    name: "Turkish Get-up",
    category: "full_body",
    primaryMuscleGroup: "Shoulders/Core",
    equipment: "Kettlebell",
    isTimed: false,
    defaultSets: 3,
    defaultRepsOrDuration: "3-5 each side",
    aliases: ["tgu"],
    youtubeSearch: "turkish+get+up+form",
  },
  {
    id: "catalog-mobility-hip-flexor-stretch",
    name: "Hip Flexor Stretch",
    category: "mobility_recovery",
    primaryMuscleGroup: "Hip Flexors",
    equipment: "Bodyweight",
    isTimed: true,
    defaultSets: 2,
    defaultRepsOrDuration: "45 sec",
    aliases: ["kneeling hip flexor stretch"],
    youtubeSearch: "hip+flexor+stretch+form",
  },
  {
    id: "catalog-mobility-hamstring-stretch",
    name: "Hamstring Stretch",
    category: "mobility_recovery",
    primaryMuscleGroup: "Hamstrings",
    equipment: "Bodyweight",
    isTimed: true,
    defaultSets: 2,
    defaultRepsOrDuration: "45 sec",
    aliases: ["seated hamstring stretch"],
    youtubeSearch: "hamstring+stretch+form",
  },
  {
    id: "catalog-mobility-thoracic-rotation",
    name: "Thoracic Rotation",
    category: "mobility_recovery",
    primaryMuscleGroup: "Thoracic Spine",
    equipment: "Bodyweight",
    isTimed: false,
    defaultSets: 2,
    defaultRepsOrDuration: "8-10 each side",
    aliases: ["t-spine rotation"],
    youtubeSearch: "thoracic+rotation+mobility",
  },
  {
    id: "catalog-mobility-couch-stretch",
    name: "Couch Stretch",
    category: "mobility_recovery",
    primaryMuscleGroup: "Quads/Hips",
    equipment: "Bench or Wall",
    isTimed: true,
    defaultSets: 2,
    defaultRepsOrDuration: "45 sec",
    aliases: ["quad couch stretch"],
    youtubeSearch: "couch+stretch+form",
  },
  {
    id: "catalog-mobility-ankle-mobility-drill",
    name: "Ankle Mobility Drill",
    category: "mobility_recovery",
    primaryMuscleGroup: "Ankles",
    equipment: "Bodyweight",
    isTimed: false,
    defaultSets: 2,
    defaultRepsOrDuration: "10 each side",
    aliases: ["ankle dorsiflexion drill"],
    youtubeSearch: "ankle+mobility+drill",
  },
  {
    id: "catalog-mobility-band-pull-apart",
    name: "Band Pull-apart",
    category: "mobility_recovery",
    primaryMuscleGroup: "Upper Back",
    equipment: "Resistance Band",
    isTimed: false,
    defaultSets: 2,
    defaultRepsOrDuration: "15-20",
    aliases: ["band pull apart"],
    youtubeSearch: "band+pull+apart+form",
  },
  {
    id: "catalog-mobility-foam-roll-quads",
    name: "Foam Roll Quads",
    category: "mobility_recovery",
    primaryMuscleGroup: "Quads",
    equipment: "Foam Roller",
    isTimed: true,
    defaultSets: 2,
    defaultRepsOrDuration: "60 sec",
    aliases: ["quad foam roll"],
    youtubeSearch: "foam+roll+quads",
  },
  {
    id: "catalog-mobility-cat-cow",
    name: "Cat-cow",
    category: "mobility_recovery",
    primaryMuscleGroup: "Spine",
    equipment: "Bodyweight",
    isTimed: false,
    defaultSets: 2,
    defaultRepsOrDuration: "8-12",
    aliases: ["cat cow"],
    youtubeSearch: "cat+cow+mobility",
  },
  {
    id: "catalog-mobility-glute-bridge-hold",
    name: "Glute Bridge Hold",
    category: "mobility_recovery",
    primaryMuscleGroup: "Glutes",
    equipment: "Bodyweight",
    isTimed: true,
    defaultSets: 3,
    defaultRepsOrDuration: "30 sec",
    aliases: ["bridge hold"],
    youtubeSearch: "glute+bridge+hold+form",
  },
  {
    id: "catalog-mobility-breathing-drill",
    name: "Breathing Drill",
    category: "mobility_recovery",
    primaryMuscleGroup: "Recovery",
    equipment: "Bodyweight",
    isTimed: true,
    defaultSets: 1,
    defaultRepsOrDuration: "3-5 min",
    aliases: ["box breathing", "diaphragmatic breathing"],
    youtubeSearch: "breathing+drill+recovery",
  },
]
